import { ACTION_STATE, ACTION_TYPES, SCOPES } from '../../../assets/strings/constants';
const { TREELINK_TYPE, SHOWS_TYPE, MUSIC_TYPE} = ACTION_TYPES;
const { SCOPE_TREE} = SCOPES;

const GET_TREE_START = `${SCOPE_TREE}/${TREELINK_TYPE}_${ACTION_STATE.START}`;
const GET_TREE_FAIL = `${SCOPE_TREE}/${TREELINK_TYPE}_${ACTION_STATE.FAIL}`;
const GET_TREE_SUCCESS = `${SCOPE_TREE}/${TREELINK_TYPE}_${ACTION_STATE.SUCCESS}`;

const GET_SHOWS_START = `${SCOPE_TREE}/${SHOWS_TYPE}_${ACTION_STATE.START}`;
const GET_SHOWS_FAIL = `${SCOPE_TREE}/${SHOWS_TYPE}_${ACTION_STATE.FAIL}`;
const GET_SHOWS_SUCCESS = `${SCOPE_TREE}/${SHOWS_TYPE}_${ACTION_STATE.SUCCESS}`;

const GET_MUSIC_START = `${SCOPE_TREE}/${MUSIC_TYPE}_${ACTION_STATE.START}`;
const GET_MUSIC_FAIL = `${SCOPE_TREE}/${MUSIC_TYPE}_${ACTION_STATE.FAIL}`;
const GET_MUSIC_SUCCESS = `${SCOPE_TREE}/${MUSIC_TYPE}_${ACTION_STATE.SUCCESS}`;

export default {
    GET_TREE_START,
    GET_TREE_SUCCESS,
    GET_TREE_FAIL,
    GET_SHOWS_START,
    GET_SHOWS_FAIL,
    GET_SHOWS_SUCCESS,
    GET_MUSIC_START,
    GET_MUSIC_FAIL,
    GET_MUSIC_SUCCESS
}